# Generated by Django 2.2.16 on 2020-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyectodwy', '0003_misionyvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionyvision',
            name='valores',
            field=models.TextField(default=1),
        ),
    ]
