# Generated by Django 2.2.16 on 2020-10-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miProyectodwy', '0004_misionyvision_valores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misionyvision',
            name='valores',
        ),
    ]
