# Generated by Django 2.2.16 on 2020-10-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyectodwy', '0006_misionyvision_valores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagengaleria', models.ImageField(null=True, upload_to='galeria')),
            ],
        ),
    ]
